# This a bashrc for GPU4.8
# Customized settings for GPU
export PATH=.:/usr/mpi/gcc/openmpi-4.1.0rc5/bin:/opt/oci-hpc/nccl-tests/build:/usr/sbin:$PATH
export LD_LIBRARY_PATH=/usr/mpi/gcc/openmpi-4.1.0rc5/lib:$LD_LIBRARY_PATH
export MPI_HOME=/usr/mpi/gcc/openmpi-4.1.0rc5
export CUDA_HOME=/usr/local/cuda

